restore-comm: add --dry-run cmdline option to operate local-only

diff --git a/restore-comm b/restore-comm
--- a/restore-comm
+++ b/restore-comm
@@ -32,9 +32,14 @@ my $USAGE = "Usage:
 
   $0 -m|--print-mms-rsync
     print mms rsync command
+
+  $0 -s|-n|--local|--dry-run
+    create the commhistory db and fill it in LOCALLY
+    do not copy any files or write any data to the phone
 ";
 
 my $CMD_PRINT_MMS_RSYNC = "print-mms-rsync";
+my $CMD_DRY_RUN = "dry-run";
 my $CMD_APPLY = "apply";
 
 sub main(@){
@@ -46,6 +51,8 @@ sub main(@){
       exit 0;
     }elsif($arg =~ /^(-m|--print-mms-rsync)$/){
       $cmd = $CMD_PRINT_MMS_RSYNC;
+    }elsif($arg =~ /^(-n|-s|--dry-run|--local)$/){
+      $cmd = $CMD_DRY_RUN;
     }elsif($arg =~ /^(--apply)$/){
       $cmd = $CMD_APPLY;
     }else{
@@ -55,9 +62,14 @@ sub main(@){
 
   die "$USAGE\nERROR missing command\n" if not defined $cmd;
 
-  my $host = `ipmagic $IPMAGIC_NAME`;
-  die "failed to get host" if $? != 0;
-  chomp $host;
+  my $host;
+  if($cmd ne $CMD_DRY_RUN){
+    $host = `ipmagic $IPMAGIC_NAME`;
+    die "failed to get host" if $? != 0;
+    chomp $host;
+  }else{
+    $host = "DRY_RUN_NO_HOST";
+  }
 
   my $now = `date +'%Y-%m-%d_%s'`;
   chomp $now;
@@ -72,7 +84,7 @@ sub main(@){
       "$USER\@$host:$MMS_PARTS_REMOTE_DIR/"
     );
     print "@cmd\n";
-  }elsif($cmd eq $CMD_APPLY){
+  }elsif($cmd eq $CMD_APPLY or $cmd eq $CMD_DRY_RUN){
     run "cat $EMPTY_COMMHISTORY_DB_DUMP | sqlite3 $commhistoryDb";
     run "$CMD_RECENT_COMM --sms > $recentSms";
     run "$CMD_RECENT_COMM --calls > $recentCalls";
@@ -81,30 +93,37 @@ sub main(@){
     run "$CMD_SMS_DB_IMPORTER import-to-db-calls $commhistoryDb $recentCalls";
     run "$CMD_SMS_DB_IMPORTER import-to-db-mms $commhistoryDb $MMS_MSG_REPO $MMS_PARTS_REPO";
 
-    my $remoteCommhistoryDb = "/tmp/recent-$now-commhistory.db";
-    run "scp", $commhistoryDb, "$USER\@$host:$remoteCommhistoryDb";
+    if($cmd eq $CMD_DRY_RUN){
+      print "\n\nDRY RUN COMPLETE\n";
+      print "prepared commhistory DB: $commhistoryDb\n";
+    }elsif($cmd eq $CMD_APPLY){
+      my $remoteCommhistoryDb = "/tmp/recent-$now-commhistory.db";
+      run "scp", $commhistoryDb, "$USER\@$host:$remoteCommhistoryDb";
 
-    run "rsync", "-avP", "--exclude=.git",
-      "$MMS_PARTS_REPO/",
-      "$USER\@$host:$MMS_PARTS_REMOTE_DIR/";
-    run "ssh", "root\@$host", "chown $USER.$USER -R $MMS_PARTS_REMOTE_DIR/";
+      run "rsync", "-avP", "--exclude=.git",
+        "$MMS_PARTS_REPO/",
+        "$USER\@$host:$MMS_PARTS_REMOTE_DIR/";
+      run "ssh", "root\@$host", "chown $USER.$USER -R $MMS_PARTS_REMOTE_DIR/";
 
 
-    my $backupDir = "$COMMHISTORY_DB_REMOTE_DIR/commhistory-backup-$now";
-    run "ssh", "root\@$host", "
-      mkdir $backupDir && \
-      chown $USER.$USER $backupDir && \
-      mv $COMMHISTORY_DB_REMOTE_DIR/commhistory.db* $backupDir && \
-      gzip $backupDir/commhistory.db*
-      mv $remoteCommhistoryDb $COMMHISTORY_DB_REMOTE_DIR/commhistory.db && \
-      chown $USER.$USER $COMMHISTORY_DB_REMOTE_DIR/commhistory.db && \
-      echo success || ( echo FAILED TO REPLACE COMMHISTORY DB && exit 1 )
-    ";
+      my $backupDir = "$COMMHISTORY_DB_REMOTE_DIR/commhistory-backup-$now";
+      run "ssh", "root\@$host", "
+        mkdir $backupDir && \
+        chown $USER.$USER $backupDir && \
+        mv $COMMHISTORY_DB_REMOTE_DIR/commhistory.db* $backupDir && \
+        gzip $backupDir/commhistory.db*
+        mv $remoteCommhistoryDb $COMMHISTORY_DB_REMOTE_DIR/commhistory.db && \
+        chown $USER.$USER $COMMHISTORY_DB_REMOTE_DIR/commhistory.db && \
+        echo success || ( echo FAILED TO REPLACE COMMHISTORY DB && exit 1 )
+      ";
 
-    print "RESTARTING PHONE! ok? [y/N] ";
-    my $line = <STDIN>;
-    if($line =~ /y|Y/){
-      run "ssh", "root\@$host", "reboot";
+      print "RESTARTING PHONE! ok? [y/N] ";
+      my $line = <STDIN>;
+      if($line =~ /y|Y/){
+        run "ssh", "root\@$host", "reboot";
+      }
+    }else{
+      die "ERROR: failed to parse command $cmd\n";
     }
   }else{
     die "$USAGE\nERROR: unknown command $cmd\n";
