sync-home-config: merge changes from raspi- single initial/final commands, fail on error, split special user/root

diff --git a/sync-home-config b/sync-home-config
--- a/sync-home-config
+++ b/sync-home-config
@@ -31,7 +31,7 @@ my @USRLOCALBIN_EXECS = qw(
 my $HOMEBIN_LOCAL_DIR = "$ENV{HOME}/bin";
 my $HOMEBIN_REMOTE_DIR = "/home/$user/bin";
 
-my @SPECIAL_RSYNCS = (
+my @SPECIAL_USER_RSYNCS = (
   ["$ENV{HOME}/.klomp/config-$ipmagicName", "/home/$user/.klomp/config"],
   ["$ENV{HOME}/.klomp/lib-$ipmagicName", "/home/$user/.klomp/lib"],
   ["$ENV{HOME}/Music/sheet_music/shows/sheet_1080p/", "/media/sdcard/phone/sheet_music/shows/sheet_1080p/"],
@@ -40,24 +40,30 @@ my @SPECIAL_RSYNCS = (
   ["/usr/share/alarms/", "/media/sdcard/phone/alarms/"],
   ["/usr/share/sounds/custom/", "/media/sdcard/phone/sounds/"],
 );
-
-my @INITIAL_USER_CMDS = (
-  "mkdir -p /home/$user/.config/qtemail",
-  "mkdir -p /home/$user/.klomp",
-);
-my @FINAL_USER_CMDS = (
+my @SPECIAL_ROOT_RSYNCS = (
 );
 
-my @INITIAL_ROOT_CMDS = (
-  "mkdir -p /root/.config/qtemail",
-  "rmdir /root/bin 2>/dev/null",
-  "rm -f /root/bin",
-  "ln -s /home/$user/bin/ /root/bin",
-);
-my @FINAL_ROOT_CMDS = (
-  "sed -i 's/›/>/g' /home/$user/.vimrc",
-  "sed -i 's/›/>/g' /root/.vimrc",
-);
+my $INITIAL_USER_CMD = "
+  mkdir -p /home/$user/.config/qtemail && \
+  mkdir -p /home/$user/.klomp && \
+  echo ok
+";
+my $FINAL_USER_CMD = "
+  echo ok
+";
+
+my $INITIAL_ROOT_CMD = "
+  mkdir -p /root/.config/qtemail && \
+  if [ -L /root/bin ]; then rm -f /root/bin; fi && \
+  if [ -d /root/bin ]; then rmdir /root/bin; fi && \
+  ln -s /home/$user/bin/ /root/bin && \
+  echo ok
+";
+my $FINAL_ROOT_CMD = "
+  sed -i 's/›/>/g' /home/$user/.vimrc && \
+  sed -i 's/›/>/g' /root/.vimrc && \
+  echo ok
+";
 
 sub run(@);
 
@@ -72,12 +78,8 @@ sub main(@){
   chomp $host;
 
   print "\n\n===INITIAL COMMANDS\n";
-  for my $cmd(@INITIAL_USER_CMDS){
-    run "ipmagic", $ipmagicName, "-u", $user, $cmd;
-  }
-  for my $cmd(@INITIAL_ROOT_CMDS){
-    run "ipmagic", $ipmagicName, "-u", "root", $cmd;
-  }
+  run "ipmagic", $ipmagicName, "-u", $user, $INITIAL_USER_CMD;
+  run "ipmagic", $ipmagicName, "-u", "root", $INITIAL_ROOT_CMD;
 
   print "\n\n===RSYNC /usr/local/bin FILES\n";
   my @usrlocalbinFiles = map {"$USRLOCALBIN_LOCAL_DIR/$_"} @USRLOCALBIN_EXECS;
@@ -93,23 +95,26 @@ sub main(@){
   }
 
   print "\n\n===RSYNC SPECIAL FILES\n";
-  for my $rsync(@SPECIAL_RSYNCS){
+  for my $rsync(@SPECIAL_USER_RSYNCS){
     my ($src, $dest) = @$rsync;
     run "rsync", "-avP", $src, "$user\@$host:$dest";
   }
+  for my $rsync(@SPECIAL_ROOT_RSYNCS){
+    my ($src, $dest) = @$rsync;
+    run "rsync", "-avP", $src, "root\@$host:$dest";
+  }
 
   print "\n\n===FINAL COMMANDS\n";
-  for my $cmd(@FINAL_USER_CMDS){
-    run "ipmagic", $ipmagicName, "-u", $user, $cmd;
-  }
-  for my $cmd(@FINAL_ROOT_CMDS){
-    run "ipmagic", $ipmagicName, "-u", "root", $cmd;
-  }
+  run "ipmagic", $ipmagicName, "-u", $user, $FINAL_USER_CMD;
+  run "ipmagic", $ipmagicName, "-u", "root", $FINAL_ROOT_CMD;
 }
 
 sub run(@){
   print "@_\n";
   system @_;
+  if($? != 0){
+    die "ERROR: \"@_\" failed\n";
+  }
 }
 
 &main(@ARGV);
